version: '3'
services:
    mysql:
        image: mysql:8-oracle
        container_name: gramacheck
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=Fine@123
            - MYSQL_DATABASE=gramacheck
            - MYSQL_USER=root
            - MYSQL_PASSWORD=Fine@123
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 1m30s
            timeout: 20s
            retries: 5
        ports:
            - "3307:3306"
        volumes:
            - "./generated/db/script.sql:/docker-entrypoint-initdb.d/1.sql"
            - "./data-seeds.sql:/docker-entrypoint-initdb.d/2.sql"
